apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
  namespace: filedepot
  labels:
    app: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: data
        image: filedepot-data:local
        envFrom:
        - configMapRef:
            name: filedepot-env
        ports:
        - containerPort: 8002
        readinessProbe:
          httpGet:
            path: /ping
            port: 8002
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data
  namespace: filedepot
spec:
  selector:
    app: data
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
